--1. 사용자정보 T_MEMBER
DROP TABLE T_MEMBER;
DROP SEQUENCE T_MEMBER_SEQ;
CREATE SEQUENCE T_MEMBER_SEQ;
CREATE TABLE T_MEMBER
( 
    MEMBER_NO NUMBER DEFAULT T_MEMBER_SEQ.NEXTVAL CONSTRAINT MEMBER_MEMBER_NO_PK PRIMARY KEY,
    ID VARCHAR2(100) CONSTRAINT MEMBER_ID_UK UNIQUE,
    PW VARCHAR2(20) CONSTRAINT MEMBER__PW_NN NOT NULL,
    NAME VARCHAR2(20) CONSTRAINT NAME_NN NOT NULL,
    MOBILE_NO VARCHAR2(20) CONSTRAINT MEMBER_NO_NN NOT NULL,
    RRN VARCHAR2(20) CONSTRAINT MEMBER_RRN_UK UNIQUE,
    BIRTHDAY VARCHAR2(20) CONSTRAINT MEMBER_BIRTHDAY_NN NOT NULL,
    AGE NUMBER CONSTRAINT MEMBER_AGE_NN NOT NULL,
    GENDER VARCHAR2(20) CONSTRAINT MEMBER_GENDER_NN NOT NULL CHECK (GENDER IN ('F', 'M')),
    ISNATIVE VARCHAR2(20) CONSTRAINT MEMBER_NATIVE_NN NOT NULL CHECK (ISNATIVE IN ('N', 'F')),
    MANAGER_NO NUMBER DEFAULT NULL,
    USER_TYPE VARCHAR2(20) DEFAULT 'U' CONSTRAINT MEMBER_USER_TYPE_NN NOT NULL CHECK (USER_TYPE IN ('U', 'A')) ,
    ADDRESS VARCHAR2(100) CONSTRAINT MEMBER_USER_ADDRESS_NN NOT NULL,
    ADDRESS_DETAIL VARCHAR2(100) CONSTRAINT MEMBER_ADDRESS_DETAIL_NN NOT NULL
);

ALTER TABLE T_MEMBER ADD ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL;

ALTER TABLE T_MEMBER ADD EMAIL_ADDRESS VARCHAR2(100) DEFAULT 'test@gmail.com' NOT NULL;
SELECT * FROM T_MEMBER;
update t_member set ENROLL_DATE = ENROLL_DATE - 39 where member_no>4000;
commit;
DESC T_MEMBER;
-----------------------------------
--2. 카드 CARD

DROP TABLE CARD;
CREATE TABLE CARD (
    CARD_CODE NUMBER(10) CONSTRAINT CARD_CARD_CODE_PK PRIMARY KEY, 
    CARD_NAME VARCHAR2(200) CONSTRAINT CARD_CARD_NAME_UK UNIQUE,
    CARD_TYPE VARCHAR2(20),
    ANNUAL_FEE NUMBER(10)
);
commit;
SELECT * FROM CARD WHERE CARD_TYPE='CHECK' ORDER BY CARD_CODE;



-----------------------------------
--3. 혜택카테고리 (BENEFITS_CATEGORY)
DROP TABLE CARD_BENEFITS_CATEGORY;
CREATE TABLE CARD_BENEFITS_CATEGORY (
    CATEGORY VARCHAR2(50) CONSTRAINT BENEFTIS_CATEGORY_PK PRIMARY KEY,
    CATEGORY_KOR VARCHAR2(200)
);

-----------------------------------
--4. 카드 혜택 (CARD_BENEFTIS)
DROP SEQUENCE CARD_BENEFITS_SEQ;
DROP TABLE CARD_BENEFITS;

CREATE SEQUENCE CARD_BENEFITS_SEQ;



CREATE TABLE CARD_BENEFITS(
    BENEFITS_NO NUMBER DEFAULT CARD_BENEFITS_SEQ.NEXTVAL CONSTRAINT CARD_BENEFITS_PK PRIMARY KEY,
    "CARD_NAME" VARCHAR2(200) , 
	"MOVIE" NUMBER, 
	"SHOPPING" NUMBER, 
	"COMMUNICATION" NUMBER, 
	"EDUCATION" NUMBER, 
	"HYPERMART" NUMBER, 
	"MAINTENANCE" NUMBER, 
	"AUTOMOBILES" NUMBER, 
	"MEDICAL" NUMBER, 
	"CULTURE" NUMBER, 
	"FINANCE" NUMBER, 
	"AIR_MILEAGE" NUMBER, 
	"CAFE_BAKERY" NUMBER, 
	"ALWAYS_DISCOUNT" NUMBER, 
	"VOUCHER" NUMBER, 
	"PRIORITY_PASS" NUMBER, 
	"PREMIUM" NUMBER, 
	"OIL" NUMBER, 
	"PUBLIC_TRANSPORTATION" NUMBER, 
	"ANNUAL_FEE_SUPPORT" NUMBER, 
	"EAT_OUT" NUMBER, 
	"LEISURE" NUMBER, 
	"POINT_CASHBACK" NUMBER, 
	"EASY_PAY" NUMBER, 
	"BEAUTY" NUMBER, 
	"NATIONAL_VOUCHER" NUMBER, 
	"CVS" NUMBER,
    "RENTAL" NUMBER,
    CONSTRAINT CARD_BENEFITS_CARD_NAME_FK FOREIGN KEY (CARD_NAME) REFERENCES CARD(CARD_NAME)
    );
    
   

SELECT * FROM CARD_BENEFITS;
-----------------------------------
--5. 신용카드 공지 (CREDIT_CARD_NOTICE)
DROP SEQUENCE CREDITCARD_NOTICE_SEQ;
DROP TABLE CREDITCARD_NOTICE;

CREATE SEQUENCE CREDITCARD_NOTICE_SEQ;
CREATE TABLE CREDITCARD_NOTICE (
    NOTICE_NO NUMBER DEFAULT CREDITCARD_NOTICE_SEQ.NEXTVAL CONSTRAINT CREDITCARD_NOTICE_PK PRIMARY KEY,
    CARD_NAME VARCHAR2(200),
    CATEGORY VARCHAR2(50),
    NOTICE VARCHAR2(300) CONSTRAINT CREDITCARD_NOTICE_NOTICE_NN NOT NULL,
    CONSTRAINT CREDITCARD_NOTICE_CARD_NAME_FK FOREIGN KEY (CARD_NAME) REFERENCES CARD(CARD_NAME),
    CONSTRAINT CREDITCARD_NOTICE_CARD_CATEGORY_FK FOREIGN KEY (CATEGORY) REFERENCES CARD_BENEFITS_CATEGORY(CATEGORY)
);

SELECT * FROM CREDITCARD_NOTICE;



-----------------------------------
--6. 사용자카드 MEMBER_CARD
DROP SEQUENCE MEMBER_CARD_SEQ;
DROP TABLE MEMBER_CARD;

CREATE SEQUENCE MEMBER_CARD_SEQ;
CREATE TABLE MEMBER_CARD
(
    CARD_ENROLL_NO NUMBER DEFAULT MEMBER_CARD_SEQ.NEXTVAL CONSTRAINT MEMBER_CARD_CARD_ENROLL_NO_PK PRIMARY KEY,
    CARD_NO VARCHAR2(30) CONSTRAINT MEMBER_CARD_CARD_NO_UK UNIQUE,
    MEMBER_NO NUMBER,
    CARD_CODE NUMBER(30),
    CARD_PASSWORD VARCHAR2(20) CONSTRAINT MEMBER_CARD_CARD_PASSWORD_NN NOT NULL,
    VALID_DATE DATE CONSTRAINT MEMBER_CARD_VALID_DATE_NN NOT NULL,
    CVC_NO VARCHAR2(30) CONSTRAINT MEMBER_CARD_CARD_CVV_NO_NN NOT NULL, 
    CONSTRAINT MEMBER_CARD_MEMBER_NO_FK FOREIGN KEY(MEMBER_NO) REFERENCES T_MEMBER(MEMBER_NO),
    CONSTRAINT MEMBER_CARD_CODE_NAME_FK FOREIGN KEY(CARD_CODE) REFERENCES CARD(CARD_CODE)
);

ALTER TABLE MEMBER_CARD ADD ENROLL_CARD_DATE DATE DEFAULT SYSDATE;

-----------------------------------
--7. 사용자거래내역 TRANSACTION_HISTORY
DROP TABLE TRANSACTION_HISTORY;
DROP SEQUENCE TRANSACTION_HISTORY_SEQ;
SELECT TRANSACTION_HISTORY_SEQ.CURRVAL FROM DUAL;
CREATE SEQUENCE TRANSACTION_HISTORY_SEQ START WITH 234916;

CREATE TABLE TRANSACTION_HISTORY
(

    HISTORY_NO NUMBER DEFAULT TRANSACTION_HISTORY_SEQ.NEXTVAL CONSTRAINT TRANSACTION_HISTORY_HISTORY_NO_PK PRIMARY KEY,
    HISTORY_DATE DATE DEFAULT SYSDATE CONSTRAINT TRANSACTION_HISTORY_HISTORY_DATE_NN NOT NULL,
    AMOUNT NUMBER CONSTRAINT TRANSACTION_HISTORY_AMOUNT_NN NOT NULL,
    CATEGORY VARCHAR2(30),
    HISTORY_TIME VARCHAR2(30) CONSTRAINT TRANSACTION_HISTORY_HISTORY_TIME_NN NOT NULL,
    STORE VARCHAR2(1000),
    CARD_NO VARCHAR2(20),
    CONSTRAINT TRANSACTION_HISTORY_CARD_NO_FK FOREIGN KEY(CARD_NO) REFERENCES MEMBER_CARD(CARD_NO)
);










